---
title: "Do Pasto ao Prato Exercise"
author: "Willian Vieira"
date: today
format:
  html:
    theme: cosmo
    toc: true
---

```{r setup, include=FALSE}
# Cache chunks
knitr::opts_chunk$set(cache = TRUE)
```

# Task 1: Distribution of meat suppliers by state

## Query data

```{r import packages,message=FALSE}
library(httr)
library(glue)
library(tibble)
library(purrr)
library(dplyr)
library(tidyr)
library(stringr)
library(sf)
library(ggplot2)
```


```{r parameters}
api_endpoint = 'http://compras.dados.gov.br/fornecedores/v1/fornecedores.'
format_type = 'csv' # available types: `html`, `xml`, `json`, or `csv`
col_id = 'id_cnae'
# Classes of economic activity
CNAE_ids <- c('1011201', '1011205', '1013901', '1013902')
```

Now let's query the suppliers of meat to each CNAE activitiy classes.

```{r query suppliers,message=FALSE}
# Query data
suppliers_ls = map(
  CNAE_ids,
  ~ GET(glue('{api_endpoint}{format_type}?{col_id}={.x}'))
)

# Check if all queries were correct (200 code)
query_status <- map(suppliers_ls, ~ status_code(.)) |>
  flatten_int()

# keep only the ones that did not fail
suppliers_ls <- suppliers_ls[query_status == 200]

# Extract query content and convert to a single data.frame
suppliers_dt = map(
    suppliers_ls,
    ~ content(.x)
  ) |>
  bind_rows()
```


## Number of suppliers by state

```{r, compute nbSuppliers}
# compute number of suppliers by state
nbSuppliers_state <- suppliers_dt |>
  group_by(UF) |>
  summarise(
    nbSuppliers = length(unique(CNPJ))
  )
```

::: {#figBarMap}

```{r, barPlot,message=FALSE,fig.width=12,fig.height=13}
#| layout-ncol: 2

nbSuppliers_state |>
  left_join(
    read.csv(file.path('data', 'states.csv'))
  ) |>
  ggplot(aes(y = reorder(StateName, nbSuppliers), x = nbSuppliers, fill = nbSuppliers)) +
    geom_col() +
    scale_fill_viridis_c() +
    theme_classic() +
    ylab('') + xlab('') +
    labs(title = 'Number of suppliers by state') +
    theme(
      legend.position = 'none',
      text = element_text(size = 36)
    )

readRDS(file.path('data', 'statesPolygon.RDS')) |>
  left_join(
    nbSuppliers_state,
    by = c('abbrev_state' = 'UF')
  ) |>
  ggplot() +
    geom_sf(aes(fill = nbSuppliers)) +
    scale_fill_viridis_b() +
    theme_classic() +
    theme(
      axis.line=element_blank(),
      axis.title=element_blank(),
      axis.text=element_blank(),
      axis.ticks=element_blank(),
      legend.title=element_blank(),
      legend.position = 'bottom',
      text = element_text(size = 26),
      legend.key.size = unit(1, 'cm')
    )
```

Distribution of meat suppliers by Brazilian states.

:::